import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import GoogleTranslatePatch from "@/components/GoogleTranslatePatch";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chedesnyo | Dashboard",
  description: "Generated by Chedesnyo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleTranslatePatch />
        <div id="google_translate_element" style={{ display: 'none' }} />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
