import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppProvider from "@/provider/AppProvider";
import GoogleTranslatePatch from "@/components/GoogleTranslatePatch";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chedesnyo | Dashboard",
  description: "Generated by Chedesnyo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl" suppressHydrationWarning>
      <head>
        <script src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" async />
        <script dangerouslySetInnerHTML={{ __html: `
          function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'nl', includedLanguages: 'nl,en', autoDisplay: false}, 'google_translate_element');
          }
          window.__GOOGLE_TRANSLATION_CONFIG__ = { languages: [{title:'Nederlands',name:'nl'},{title:'English',name:'en'}], defaultLanguage:'nl' };
          window.dispatchEvent(new Event('translationConfigReady'));
        `}} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleTranslatePatch />
        <div id="google_translate_element" style={{ display: 'none' }} />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
